# Site settings
name: Primordial Analytics
title: Primordial Analytics
tagline: "AI-focused Analytics"
email: contact@primordialanalytics.com
description: "Primordial Analytics Consulting is an AI-focused analytics firm."
blogurl: "/blog/"
baseurl: ""
url: https://www.primordialanalytics.com
permalink: pretty
markdown: kramdown
highlighter: rouge

# add collections
collections:
  casestudies:
  posts:
    output: true
    permalink: /blog/:title/

# add other dirs
includes:
- vendor
- favicons
- fonts
- img
- js

# exclude other dirs
exclude:
- node_modules
- gulpfile.js
- gulpfile_example.js
- README.md
- svg
- .idea

# Team names, titles and social links
people:
- name: Ken Cavagnolo
  pic: cavagnolo.png
  position: Chief Data Scientist
  social:
    - icon: fab fa-linkedin-in
      url: https://www.linkedin.com/in/kencavagnolo
    - icon: fab fa-github-alt
      url: https://github.com/kcavagnolo
    - icon: fas fa-user
      url: https://www.kcavagnolo.com

- name: Coming soon
  pic: anon.png
  position: Chief AI Engineer
  social:
    - icon: fab fa-linkedin-in
      url: #
    - icon: fab fa-github-alt
      url: #
    - icon: fas fa-robot
      url: #

- name: Coming soon
  pic: anon.png
  position: Chief Data Engineer
  social:
    - icon: fab fa-linkedin-in
      url: #
    - icon: fab fa-github-alt
      url: #
    - icon: fab fa-stack-overflow
      url: #

# Social networks usernames
social:
  - icon: fab fa-twitter
    url: https://twitter.com/primordialytics
  - icon: fab fa-facebook-f
    url: https://fb.me/primordialytics
  - icon: fab fa-linkedin-in
    url: https://linkedin.com/company/primordial-analytics/
  - icon: fab fa-github-alt
    url: https://github.com/primordial-analytics

# Postal address
address:
  - line: Technology Drive
  - line: Knoxville, TN 37932
