# Site settings
name: Primordial Analytics
title: AI Consulting and Analytics | Primordial Analytics
tagline: "AI Consulting and Analytics"
email: contact@primordialanalytics.com
description: "Primordial Analytics delivers cutting-edge AI solutions, advanced machine learning, and predictive analytics, empowering businesses to unlock data-driven success."
lang: en
blogurl: "/blog/"
baseurl: ""
url: https://www.primordialanalytics.com
permalink: pretty
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# add collections
collections:
  team:
    output: true
  testimonials:
    output: true
  casestudies:
    output: true
  posts:
    output: true
    permalink: /blog/:title/

# add other dirs
includes:
  - favicons
  - fonts
  - img
  - js

# exclude other dirs
exclude:
  - node_modules
  - vendor/bundle/ruby/3.1.0/gems/jekyll-3.9.3/lib/site_template/_posts
  - gulpfile.js
  - gulpfile_example.js
  - README.md
  - svg
  - .idea

# Social networks usernames
social:
  - icon: fab fa-linkedin-in
    url: https://linkedin.com/company/primordial-analytics/

# Postal address
address:
  - line: Technology Drive
  - line: Portland, Oregon, USA
